---# This CF template will create VPC infra (VPC, Subnets, NACL, IGW and route53 (for private hosted zone)
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  VPCCidr:
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be a valid CIDR range in the form x.x.x.x/16. It must not overlap with any CIDR currently in use.
    Default: 10.21.0.0/16
  PublicCIDR:
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be a valid CIDR range in the form x.x.x.x/22. It must not overlap with any CIDR currently in use.
    Default: 10.21.1.0/24 # Provides 256 hosts 10.21.1.0 - 10.21.1.255
  PrivateCIDR:
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be a valid CIDR range in the form x.x.x.x/22. It must not overlap with any CIDR currently in use.
    Default: 10.21.5.0/24 # Provides 256 hosts 10.21.5.0 - 10.21.5.255
Resources:
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref VPCCidr
  IGW:
    Type: "AWS:EC2::InternetGateway"
  GatewayAttach:
    Type: "AWS::EC2::VPCGatewayAttachement"
    Properties:
      InternetGatewayId: !Ref IGW
      VpcId: !Ref VPC
  SubnetPublic
